### ISSUE TITLE
Warning in workflow about set-output

### ISSUE THREAD

**Issue by christina-30** [actions/setup-node#609]
**So when I use "::set-output":** 
<img width="711" alt="Screen Shot 2022-10-26 at 12 20 55 pm" src="https://user-images.githubusercontent.com/112351798/197916350-00851aef-302e-4838-b8b6-a27c2dcfdef1.png">

 **I have this warning:**  
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/  

**I set my "output" in first job to be used in second job of my workflow:**
![Screen Shot 2022-10-26 at 12 21 43 pm](https://user-images.githubusercontent.com/112351798/197917110-22ce8d6c-892d-45ca-9f98-51dff3b1dcd4.png)

**I get the "VERSION" output:**
![Screen Shot 2022-10-26 at 12 21 32 pm](https://user-images.githubusercontent.com/112351798/197917278-531fe0c9-3cf2-4e20-b4bf-8ecefa62d181.png)

**Then after I updated my echo command to this:** 
![Screen Shot 2022-10-26 at 12 21 05 pm](https://user-images.githubusercontent.com/112351798/197916365-06045ec6-c464-4018-9987-bef1369f12e6.png)
**I don't have 'Version" output:** 
![Screen Shot 2022-10-26 at 12 21 14 pm](https://user-images.githubusercontent.com/112351798/197916429-7c982e92-3178-4f1d-beb9-e2200bf52e68.png)

So @jamesottaway @phishy can you please help me check which part is wrong?

**Comment by dsame** [comment]
Hello @christina-30,
thanks for your input. We need some time to investigate the problem.

**Comment by dsame** [comment]
@christina-30 

The problem is with pwsh used as a shell for the step. To access the env. variable from it it is necessary to use $Env:VAR syntax. See [here](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.2).

Thus the corrected step should look like:
```
      - name: set output via env. files
        id: someId
        shell: pwsh
        run: |
          echo "VERSION2=V2" >> $Env:GITHUB_OUTPUT
```
Sample [build](https://github.com/akv-demo/setup-node-test/actions/runs/3327640912/jobs/5502695142#step:4:1).

Please confirm i understood your problem right and it is solved.

**Comment by christina-30** [comment]
@dsame Thank you for helping me out, it's working now!  But may I ask that why I still get these warnings after I update to $Env: GITHUB_OUTPUT
![Screen Shot 2022-10-27 at 11 31 00 am](https://user-images.githubusercontent.com/112351798/198166616-a68f6a61-341f-4b30-b0a1-cbf8aaf9c6bd.png)

![Screen Shot 2022-10-27 at 11 29 35 am](https://user-images.githubusercontent.com/112351798/198166567-c0c6bac6-118e-463a-b6a1-6cb81fd9efec.png)

**Comment by dsame** [comment]
@christina-30 I guess there's still set-output variable in the pipeline.

Take a look please at the sample [pipeline build ](https://github.com/akv-demo/setup-node-test/actions/runs/3335285572)that does not produce the warning.  In order to answer the question exactly i have to see the workflow file.

**Comment by christina-30** [comment]
@dsame Thank you for your reply. My workflow job "generate_version" is below: 
![Screen Shot 2022-10-27 at 6 06 40 pm](https://user-images.githubusercontent.com/112351798/198220486-7fda9d3a-0196-43ae-a979-63ec0f5a2899.png)

**Comment by dsame** [comment]
@christina-30 there's no visible reason for the warning to appear, please address the issue to the team of[ the runner repo](https://github.com/actions/runner) - they could provide more efficient support for the question.

**Comment by dmitry-shibanov** [comment]
Hello @christina-30. Could you please for testing comment `setup@0.9.14` and `execute@0.9.14` actions ?

**Comment by christina-30** [comment]
@dmitry-shibanovHi thank you for your reply. If I comment setup@0.9.14 and execute@0.9.14 actions, may I ask that how can I run my workflow? I used   gittools/actions/gitversion/setup@v0.9.7 in other projects
<img width="431" alt="Screen Shot 2022-10-28 at 11 21 33 am" src="https://user-images.githubusercontent.com/112351798/198424094-c91cda3f-0c75-427c-bb34-aed76f392607.png">

but have this warnings
![Screen Shot 2022-10-28 at 11 20 57 am](https://user-images.githubusercontent.com/112351798/198424016-fac7ca42-6e63-4fcb-b7e5-f2f4b53c8e7b.png)

**Comment by dsame** [comment]
@dmitry-shibanov  i was able to reproduce the problem 

https://github.com/akv-demo/setup-node-test/actions/runs/3381641571/jobs/5615761441#step:5:52

It looks like the either action or one of its dependency itself is still using set-output internally

@christina-30 the warning may be ignored if your pipeline does not use `set-output` implicitly, the warning is originated from some 3rd party code that has not been updated yet.

**Comment by dsame** [comment]
Hello @christina-30 , i am closing the issue because it does not relate to setup-node repo, but please feel free to reopen it or create another one in case if feel the problem still should solved by us.

**Comment by satanshiro** [comment]
to me this happens on a very simple workflow if it's not setup node then what is it?

**Comment by dmitry-shibanov** [comment]
Hello @satanshiro. Could you please attach link to a public repository? I've tried to reproduce issue from my side but it works expected.
