### ISSUE TITLE
Node 16 deprecation

### ISSUE THREAD

**Issue by kinano** [actions/setup-node#850]
Node16 will be deprecated on 09/11/2023 ([link](https://nodejs.org/en/blog/announcements/nodejs16-eol)). 

Node 16 is used by the action at the moment according to the source code: https://github.com/actions/setup-node/blob/5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d/action.yml#L35-L36

Is there a plan to release a node version update soon?

**Comment by dusan-trickovic** [comment]
Hello, @kinano! Thank you for creating an issue, we'll look into this :)

**Comment by MikeMcC399** [comment]
@dusan-trickovic 

Based on the announcement [GitHub Actions: Transitioning from Node 16 to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) the current version of this JavaScript Action [v3.8.1](https://github.com/actions/setup-node/releases/tag/v3.8.1) will cause `node16` deprecation notices to be generated starting on October 23, 2023.

So apart from the fact the Node.js `16` is already in end-of-life status, it will soon start to visibly affect GitHub Action workflows using [actions/setup-node](https://github.com/actions/setup-node/) if no steps are taken to provide an updated release running on `node20`.

Please release a new version supporting `node20` as requested by @kinano!

**Comment by dusan-trickovic** [comment]
Hello @MikeMcC399! Thank you very much for your input, we are looking into this :)

**Comment by MikeMcC399** [comment]
Hello @dusan-trickovic 

> Thank you very much for your input, we are looking into this :)

Do you have any result from looking at the issue? Have you got plans to implement now?

Deprecation notices are supposed to start being displayed today.

**Comment by MikeMcC399** [comment]
- This issue is resolved through PR #866 and release of [actions/setup-node@v4.0.0](https://github.com/actions/setup-node/releases/tag/v4.0.0)

**Comment by dmitry-shibanov** [comment]
Hello everyone. The new version with support of node20 was released in [v4.0.0](https://github.com/actions/setup-node/releases/tag/v4.0.0). For now I'm going to close the issue.

**Comment by rwader-swi** [comment]
@dusan-trickovic sorry to tag but I updated my workflows like `node-version: 20` or even as `'latest'`, and in the logs it downloads the .tar or gets from cache correctly. But on the workflow run's page I still get 'Node 16 deprecated' flooded warnings. Is there anything I'm missing?

**Comment by MikeMcC399** [comment]
@rwader-swi 

You need to change `actions/setup-node@v3` to `actions/setup-node@v4` in your workflow.
